services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: mysqlMyRootPassword
      MYSQL_DATABASE: coupang_dev
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_lock_wait_timeout=1
    ports:
      - "3306:3306"
